#!/usr/bin/env node
// 把 assets/*.svg 内联为 base64 data URI，生成 src/client/assets.ts。
// 零额外依赖：readFileSync + base64。生成物提交入仓（体积小，保证单测可独立跑）。
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const assetsDir = join(here, '..', 'assets')
const outFile = join(here, '..', 'src', 'client', 'assets.ts')

/** 文件名 → 导出键映射（新资产加一行即可）。 */
const ENTRY_MAP = {
  '橙色.svg': 'ORANGE_ICON',
  '橙色logo横板文件.svg': 'ORANGE_LOGO',
  '蓝色.svg': 'BLUE_ICON',
  '蓝色logo横板文件.svg': 'BLUE_LOGO',
}

function toDataUri(fileName) {
  const path = join(assetsDir, fileName)
  const svg = readFileSync(path, 'utf8')
  if (!svg.trim().startsWith('<svg')) throw new Error(`not an svg: ${fileName}`)
  return `data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}`
}

export function buildAssets() {
  const lines = ['// AUTO-GENERATED by scripts/build-assets.mjs — do not edit by hand.', '// 源文件：assets/*.svg（VoltClaw 官方 Logo，双色品牌标，原样内联）。', '']
  for (const [file, key] of Object.entries(ENTRY_MAP)) {
    if (!statSync(join(assetsDir, file), { throwIfNoEntry: false })) throw new Error(`missing asset: ${file}`)
    lines.push(`export const ${key} = '${toDataUri(file)}'`)
  }
  lines.push('', 'export interface ThemeAssets { icon: string; logo: string }', '')
  lines.push('export const ASSETS = {', "  orange: { icon: ORANGE_ICON, logo: ORANGE_LOGO },")
  lines.push("  blue: { icon: BLUE_ICON, logo: BLUE_LOGO },", '} as const satisfies Record<string, ThemeAssets>')
  lines.push('')
  writeFileSync(outFile, lines.join('\n'), 'utf8')
  return outFile
}

if (process.argv[1] && process.argv[1].endsWith('build-assets.mjs')) {
  const out = buildAssets()
  console.log(`assets.ts written: ${out} (${readdirSync(assetsDir).length} svgs)`)
}
